FROM mcr.microsoft.com/playwright:v1.43.1-jammy

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npx playwright install --with-deps

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start", "--", "-H", "0.0.0.0"]
