FROM mcr.microsoft.com/playwright:v1.52.0-jammy

WORKDIR /app

COPY ./package*.json ./
RUN npm install

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_BASE

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}

COPY . .

RUN echo "Building with API: ${NEXT_PUBLIC_API_URL}"

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start", "--", "-H", "0.0.0.0"]
