- name: Install Datadog Agent
  hosts: webservers
  become: true

  roles:
    - role: datadog.datadog

  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
      tags:
        - env:production
        - role:web
      log_enabled: true
      apm_config:
        enabled: true
    datadog_checks:
      http_check:
        init_config: {}
        instances:
          - name: Frontend Homepage
            url: "http://localhost:3000"
            timeout: 5
            method: GET
            http_response_status_code: 200
            tags:
              - service:frontend
    datadog_manage_config: false
    datadog_disable_untracked_checks: true
