name: Playwright Tests (Docker)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create backend .env.docker
      run: |
        mkdir -p backend
        cat <<EOF > backend/.env.docker
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_HOST=db
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        SESSION_SECRET=${{ secrets.SESSION_SECRET }}
        EOF

    - name: Create frontend .env.docker
      run: |
        mkdir -p frontend
        cat <<EOF > frontend/.env.docker
        NEXT_PUBLIC_APP_ENV=production
        NEXT_PUBLIC_API_URL=http://backend:5001/api
        NEXT_PUBLIC_API_BASE=http://backend:5001
        EOF

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: make docker-build

    - name: Run containers
      run: make docker-run

    - name: Print .env.docker
      run: cat backend/.env.docker

    - name: Run DB migrations
      run: docker exec -e NODE_ENV=docker social_network-backend-1 node dist/scripts/migrate.js

    - name: Seed the database
      run: docker exec -e NODE_ENV=docker social_network-backend-1 node dist/scripts/seed.js

    - name: Wait for frontend to be ready from within container
      run: |
        docker exec social_network-frontend-1 bash -c 'until curl -sSf http://localhost:3000 > /dev/null; do sleep 1; done'

    - name: Run Playwright tests (inside frontend container)
      run: docker exec -e CI=true social_network-frontend-1 npx playwright test

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report/
