name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build -w frontend

      - name: Start frontend (prod)
        run: npm run start -w frontend &
        env:
          NODE_ENV: production

      - name: Wait for frontend to be ready
        run: |
          timeout 30s bash -c 'until curl -sSf http://localhost:3000 >/dev/null; do sleep 1; done'
        shell: bash

      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30