name: Push frontend to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build frontend
        run: npm run build -w frontend

      - name: Start frontend (prod)
        run: npm run start -w frontend &
        env:
          NODE_ENV: production

      - name: Wait for frontend to be ready
        run: |
          timeout 30s bash -c 'until curl -sSf http://localhost:3000 >/dev/null; do sleep 1; done'
        shell: bash

      - name: Run frontend e2e tests
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5001/api
          NEXT_PUBLIC_APP_ENV: test
        run: make test-e2e

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          file: ./frontend/Dockerfile.production
          tags: zyabridos/social_network_frontend:latest